// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSsHRJ6SRywcgavrYnWjsNIBt1Hzrq61U',
    appId: '1:804108364296:web:0cedc9f4cd8e0af4b43fbd',
    messagingSenderId: '804108364296',
    projectId: 'store-app-d6fdd',
    authDomain: 'store-app-d6fdd.firebaseapp.com',
    storageBucket: 'store-app-d6fdd.appspot.com',
    measurementId: 'G-9LQ93TM6B5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByjBNEhPTsaNKmxtiR1uUsChcK1C37lnk',
    appId: '1:804108364296:android:5a9e54ab8cad0eb3b43fbd',
    messagingSenderId: '804108364296',
    projectId: 'store-app-d6fdd',
    storageBucket: 'store-app-d6fdd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWgakGY6bSALQeoTgvuyM5FqS4RPuzOCE',
    appId: '1:804108364296:ios:d1020ccd094c17abb43fbd',
    messagingSenderId: '804108364296',
    projectId: 'store-app-d6fdd',
    storageBucket: 'store-app-d6fdd.appspot.com',
    iosBundleId: 'com.example.storeTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWgakGY6bSALQeoTgvuyM5FqS4RPuzOCE',
    appId: '1:804108364296:ios:d1020ccd094c17abb43fbd',
    messagingSenderId: '804108364296',
    projectId: 'store-app-d6fdd',
    storageBucket: 'store-app-d6fdd.appspot.com',
    iosBundleId: 'com.example.storeTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSsHRJ6SRywcgavrYnWjsNIBt1Hzrq61U',
    appId: '1:804108364296:web:ffb2a1fd5b11dda0b43fbd',
    messagingSenderId: '804108364296',
    projectId: 'store-app-d6fdd',
    authDomain: 'store-app-d6fdd.firebaseapp.com',
    storageBucket: 'store-app-d6fdd.appspot.com',
    measurementId: 'G-HGGRDT0LLW',
  );

}